# Generated by Django 4.2.11 on 2024-06-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_post_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="thumbnail",
            field=models.URLField(blank=True, null=True, verbose_name="썸네일"),
        ),
    ]
